/*

Copyright 2018 This Project Authors.

Author:  seanchann <seanchann@foxmail.com>

See docs/ for more information about the  project.

*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/seanchann/sample-apiserver/pkg/apis/sample/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTests implements TestInterface
type FakeTests struct {
	Fake *FakeSampleV1alpha1
	ns   string
}

var testsResource = schema.GroupVersionResource{Group: "sample", Version: "v1alpha1", Resource: "tests"}

var testsKind = schema.GroupVersionKind{Group: "sample", Version: "v1alpha1", Kind: "Test"}

// Get takes name of the test, and returns the corresponding test object, and an error if there is any.
func (c *FakeTests) Get(name string, options v1.GetOptions) (result *v1alpha1.Test, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(testsResource, c.ns, name), &v1alpha1.Test{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Test), err
}

// List takes label and field selectors, and returns the list of Tests that match those selectors.
func (c *FakeTests) List(opts v1.ListOptions) (result *v1alpha1.TestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(testsResource, testsKind, c.ns, opts), &v1alpha1.TestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TestList{ListMeta: obj.(*v1alpha1.TestList).ListMeta}
	for _, item := range obj.(*v1alpha1.TestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tests.
func (c *FakeTests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(testsResource, c.ns, opts))

}

// Create takes the representation of a test and creates it.  Returns the server's representation of the test, and an error, if there is any.
func (c *FakeTests) Create(test *v1alpha1.Test) (result *v1alpha1.Test, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(testsResource, c.ns, test), &v1alpha1.Test{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Test), err
}

// Update takes the representation of a test and updates it. Returns the server's representation of the test, and an error, if there is any.
func (c *FakeTests) Update(test *v1alpha1.Test) (result *v1alpha1.Test, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(testsResource, c.ns, test), &v1alpha1.Test{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Test), err
}

// Delete takes name of the test and deletes it. Returns an error if one occurs.
func (c *FakeTests) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(testsResource, c.ns, name), &v1alpha1.Test{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(testsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.TestList{})
	return err
}

// Patch applies the patch and returns the patched test.
func (c *FakeTests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Test, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(testsResource, c.ns, name, data, subresources...), &v1alpha1.Test{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Test), err
}
