/*

Copyright 2018 This Project Authors.

Author:  seanchann <seanchann@foxmail.com>

See docs/ for more information about the  project.

*/

// Code generated by client-gen. DO NOT EDIT.

package internalversion

type TestExpansion interface{}

type UserExpansion interface{}
