/*

Copyright 2018 This Project Authors.

Author:  seanchann <seanchann@foxmail.com>

See docs/ for more information about the  project.

*/

// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"github.com/seanchann/sample-apiserver/pkg/client/clientset/internalversion/scheme"
	rest "k8s.io/client-go/rest"
)

type SampleInterface interface {
	RESTClient() rest.Interface
	TestsGetter
}

// SampleClient is used to interact with features provided by the sample group.
type SampleClient struct {
	restClient rest.Interface
}

func (c *SampleClient) Tests(namespace string) TestInterface {
	return newTests(c, namespace)
}

// NewForConfig creates a new SampleClient for the given config.
func NewForConfig(c *rest.Config) (*SampleClient, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &SampleClient{client}, nil
}

// NewForConfigOrDie creates a new SampleClient for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *SampleClient {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new SampleClient for the given RESTClient.
func New(c rest.Interface) *SampleClient {
	return &SampleClient{c}
}

func setConfigDefaults(config *rest.Config) error {
	config.APIPath = "/apis"
	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
	if config.GroupVersion == nil || config.GroupVersion.Group != scheme.Scheme.PrioritizedVersionsForGroup("sample")[0].Group {
		gv := scheme.Scheme.PrioritizedVersionsForGroup("sample")[0]
		config.GroupVersion = &gv
	}
	config.NegotiatedSerializer = scheme.Codecs

	if config.QPS == 0 {
		config.QPS = 5
	}
	if config.Burst == 0 {
		config.Burst = 10
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *SampleClient) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
