/*

Copyright 2018 This Project Authors.

Author:  seanchann <seanchann@foxmail.com>

See docs/ for more information about the  project.

*/

// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"time"

	sample "github.com/seanchann/sample-apiserver/pkg/apis/sample"
	scheme "github.com/seanchann/sample-apiserver/pkg/client/clientset/internalversion/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// TestsGetter has a method to return a TestInterface.
// A group's client should implement this interface.
type TestsGetter interface {
	Tests(namespace string) TestInterface
}

// TestInterface has methods to work with Test resources.
type TestInterface interface {
	Create(*sample.Test) (*sample.Test, error)
	Update(*sample.Test) (*sample.Test, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*sample.Test, error)
	List(opts v1.ListOptions) (*sample.TestList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *sample.Test, err error)
	TestExpansion
}

// tests implements TestInterface
type tests struct {
	client rest.Interface
	ns     string
}

// newTests returns a Tests
func newTests(c *SampleClient, namespace string) *tests {
	return &tests{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the test, and returns the corresponding test object, and an error if there is any.
func (c *tests) Get(name string, options v1.GetOptions) (result *sample.Test, err error) {
	result = &sample.Test{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tests").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Tests that match those selectors.
func (c *tests) List(opts v1.ListOptions) (result *sample.TestList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &sample.TestList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("tests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested tests.
func (c *tests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("tests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a test and creates it.  Returns the server's representation of the test, and an error, if there is any.
func (c *tests) Create(test *sample.Test) (result *sample.Test, err error) {
	result = &sample.Test{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("tests").
		Body(test).
		Do().
		Into(result)
	return
}

// Update takes the representation of a test and updates it. Returns the server's representation of the test, and an error, if there is any.
func (c *tests) Update(test *sample.Test) (result *sample.Test, err error) {
	result = &sample.Test{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("tests").
		Name(test.Name).
		Body(test).
		Do().
		Into(result)
	return
}

// Delete takes name of the test and deletes it. Returns an error if one occurs.
func (c *tests) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tests").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *tests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("tests").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched test.
func (c *tests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *sample.Test, err error) {
	result = &sample.Test{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("tests").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
