/*

Copyright 2018 This Project Authors.

Author:  seanchann <seanchann@foxmail.com>

See docs/ for more information about the  project.

*/

package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-generated-swagger-docs.sh
// AUTO-GENERATED FUNCTIONS START HERE. DO NOT EDIT.
var map_Test = map[string]string{
	"": "Test is sample struct to use our apimaster",
}

func (Test) SwaggerDoc() map[string]string {
	return map_Test
}

var map_TestList = map[string]string{
	"": "TestList is sample list struct to use our apimaster",
}

func (TestList) SwaggerDoc() map[string]string {
	return map_TestList
}

var map_TestSpec = map[string]string{
	"family": "Family is the harbor of lov",
}

func (TestSpec) SwaggerDoc() map[string]string {
	return map_TestSpec
}

// AUTO-GENERATED FUNCTIONS END HERE
