// +build !ignore_autogenerated

/*

Copyright 2018 This Project Authors.

Author:  seanchann <seanchann@foxmail.com>

See docs/ for more information about the  project.

*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	sample "github.com/seanchann/sample-apiserver/pkg/apis/sample"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Test)(nil), (*sample.Test)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Test_To_sample_Test(a.(*Test), b.(*sample.Test), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sample.Test)(nil), (*Test)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sample_Test_To_v1alpha1_Test(a.(*sample.Test), b.(*Test), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TestList)(nil), (*sample.TestList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TestList_To_sample_TestList(a.(*TestList), b.(*sample.TestList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sample.TestList)(nil), (*TestList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sample_TestList_To_v1alpha1_TestList(a.(*sample.TestList), b.(*TestList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TestSpec)(nil), (*sample.TestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TestSpec_To_sample_TestSpec(a.(*TestSpec), b.(*sample.TestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*sample.TestSpec)(nil), (*TestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_sample_TestSpec_To_v1alpha1_TestSpec(a.(*sample.TestSpec), b.(*TestSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Test_To_sample_Test(in *Test, out *sample.Test, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_TestSpec_To_sample_TestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Test_To_sample_Test is an autogenerated conversion function.
func Convert_v1alpha1_Test_To_sample_Test(in *Test, out *sample.Test, s conversion.Scope) error {
	return autoConvert_v1alpha1_Test_To_sample_Test(in, out, s)
}

func autoConvert_sample_Test_To_v1alpha1_Test(in *sample.Test, out *Test, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_sample_TestSpec_To_v1alpha1_TestSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_sample_Test_To_v1alpha1_Test is an autogenerated conversion function.
func Convert_sample_Test_To_v1alpha1_Test(in *sample.Test, out *Test, s conversion.Scope) error {
	return autoConvert_sample_Test_To_v1alpha1_Test(in, out, s)
}

func autoConvert_v1alpha1_TestList_To_sample_TestList(in *TestList, out *sample.TestList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]sample.Test)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_TestList_To_sample_TestList is an autogenerated conversion function.
func Convert_v1alpha1_TestList_To_sample_TestList(in *TestList, out *sample.TestList, s conversion.Scope) error {
	return autoConvert_v1alpha1_TestList_To_sample_TestList(in, out, s)
}

func autoConvert_sample_TestList_To_v1alpha1_TestList(in *sample.TestList, out *TestList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Test)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_sample_TestList_To_v1alpha1_TestList is an autogenerated conversion function.
func Convert_sample_TestList_To_v1alpha1_TestList(in *sample.TestList, out *TestList, s conversion.Scope) error {
	return autoConvert_sample_TestList_To_v1alpha1_TestList(in, out, s)
}

func autoConvert_v1alpha1_TestSpec_To_sample_TestSpec(in *TestSpec, out *sample.TestSpec, s conversion.Scope) error {
	out.Family = in.Family
	return nil
}

// Convert_v1alpha1_TestSpec_To_sample_TestSpec is an autogenerated conversion function.
func Convert_v1alpha1_TestSpec_To_sample_TestSpec(in *TestSpec, out *sample.TestSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_TestSpec_To_sample_TestSpec(in, out, s)
}

func autoConvert_sample_TestSpec_To_v1alpha1_TestSpec(in *sample.TestSpec, out *TestSpec, s conversion.Scope) error {
	out.Family = in.Family
	return nil
}

// Convert_sample_TestSpec_To_v1alpha1_TestSpec is an autogenerated conversion function.
func Convert_sample_TestSpec_To_v1alpha1_TestSpec(in *sample.TestSpec, out *TestSpec, s conversion.Scope) error {
	return autoConvert_sample_TestSpec_To_v1alpha1_TestSpec(in, out, s)
}
