/*

Copyright 2018 This Project Authors.

Author:  seanchann <seanchann@foxmail.com>

See docs/ for more information about the  project.

*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	internalversion "github.com/seanchann/sample-apiserver/pkg/client/clientset/internalversion/typed/sample/internalversion"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSample struct {
	*testing.Fake
}

func (c *FakeSample) Tests(namespace string) internalversion.TestInterface {
	return &FakeTests{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSample) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
