/*

Copyright 2018 This Project Authors.

Author:  seanchann <seanchann@foxmail.com>

See docs/ for more information about the  project.

*/

// Code generated by lister-gen. DO NOT EDIT.

package internalversion

// TestListerExpansion allows custom methods to be added to
// TestLister.
type TestListerExpansion interface{}

// TestNamespaceListerExpansion allows custom methods to be added to
// TestNamespaceLister.
type TestNamespaceListerExpansion interface{}

// UserListerExpansion allows custom methods to be added to
// UserLister.
type UserListerExpansion interface{}

// UserNamespaceListerExpansion allows custom methods to be added to
// UserNamespaceLister.
type UserNamespaceListerExpansion interface{}
