/*

Copyright 2018 This Project Authors.

Author:  seanchann <seanchann@foxmail.com>

See docs/ for more information about the  project.

*/

// Code generated by client-gen. DO NOT EDIT.

package versioned

import (
	samplev1alpha1 "github.com/seanchann/sample-apiserver/pkg/client/clientset/versioned/typed/sample/v1alpha1"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
	flowcontrol "k8s.io/client-go/util/flowcontrol"
)

type Interface interface {
	Discovery() discovery.DiscoveryInterface
	SampleV1alpha1() samplev1alpha1.SampleV1alpha1Interface
	// Deprecated: please explicitly pick a version if possible.
	Sample() samplev1alpha1.SampleV1alpha1Interface
}

// Clientset contains the clients for groups. Each group has exactly one
// version included in a Clientset.
type Clientset struct {
	*discovery.DiscoveryClient
	sampleV1alpha1 *samplev1alpha1.SampleV1alpha1Client
}

// SampleV1alpha1 retrieves the SampleV1alpha1Client
func (c *Clientset) SampleV1alpha1() samplev1alpha1.SampleV1alpha1Interface {
	return c.sampleV1alpha1
}

// Deprecated: Sample retrieves the default version of SampleClient.
// Please explicitly pick a version.
func (c *Clientset) Sample() samplev1alpha1.SampleV1alpha1Interface {
	return c.sampleV1alpha1
}

// Discovery retrieves the DiscoveryClient
func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	if c == nil {
		return nil
	}
	return c.DiscoveryClient
}

// NewForConfig creates a new Clientset for the given config.
func NewForConfig(c *rest.Config) (*Clientset, error) {
	configShallowCopy := *c
	if configShallowCopy.RateLimiter == nil && configShallowCopy.QPS > 0 {
		configShallowCopy.RateLimiter = flowcontrol.NewTokenBucketRateLimiter(configShallowCopy.QPS, configShallowCopy.Burst)
	}
	var cs Clientset
	var err error
	cs.sampleV1alpha1, err = samplev1alpha1.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}

	cs.DiscoveryClient, err = discovery.NewDiscoveryClientForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	return &cs, nil
}

// NewForConfigOrDie creates a new Clientset for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *Clientset {
	var cs Clientset
	cs.sampleV1alpha1 = samplev1alpha1.NewForConfigOrDie(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClientForConfigOrDie(c)
	return &cs
}

// New creates a new Clientset for the given RESTClient.
func New(c rest.Interface) *Clientset {
	var cs Clientset
	cs.sampleV1alpha1 = samplev1alpha1.New(c)

	cs.DiscoveryClient = discovery.NewDiscoveryClient(c)
	return &cs
}
